### ISSUE TITLE
SAR ADC

### ISSUE THREAD

**Issue by PyBerger** [pvvx/esp8266web#10]
Hi I'm trying to reuse your ADC implementation in one of my programs where I need fast ADC (running @150kHz)

I'm almost done adapting the code to my environment (arduino/esp8266 based) but still struggling to find what would be the correct implementation for :

```
void rom_i2c_writeReg_Mask(uint32 block, uint32 host_id, uint32 reg_add, uint32 Msb, uint32 Lsb, uint32 indata);
```

Which fails to link with my SDK...(using 1.5.1) - do you have an implementation of this that I could use ?

I also don't seem to find this in the lst file...

**Comment by 0xPIT** [comment]
did you find out why `rom_i2c_writeReg_Mask` can not be linked?
