### ISSUE TITLE
esp8266.ru

### ISSUE THREAD

**Issue by aZholtikov** [pvvx/esp8266web#19]
Форум закрылся?

**Comment by pvvx** [comment]
Неизвестно.

https://2ip.ru/a/esp8266.ru/
_91.226.83.176 (vm-9914483e.netangels.ru): Россия, Екатеринбург
Информация о домене:
Регистрация 2014-11-08 06:27:41
Истекает 2022-11-08 06:27:41_

Куда уж ESP8266 тянуть более 8 лет?

Список всех веб-сайтов, размещённых на IP-адресе 91.226.83.176
https://2ip.ru/domain-list-by-ip/91.226.83.176/

1.	[3d0.ru ](http://3d0.ru/) перейти на сайт
2.	[corework.ru ](http://corework.ru/) перейти на сайт
3.	[esp8266.ru ](http://esp8266.ru/) перейти на сайт
4.	[iotmanager.ru ](http://iotmanager.ru/) перейти на сайт
5.	[ioty.ru ](http://ioty.ru/) перейти на сайт
6.	[lab4fun.ru ](http://lab4fun.ru/) перейти на сайт
7.	[loranet.ru ](http://loranet.ru/) перейти на сайт
8.	[nobanki.ru ](http://nobanki.ru/) перейти на сайт

Похоже накрылся сервер или провайдер.
https://downradar.ru/ne-rabotaet/esp8266.ru#r-239009

https://2ip.ru/rkn-blacklist/
Сайт найден в реестре Роскомнадзора и заблокирован на территории России.

А https://reestr.rublacklist.net/ru/?q=91.226.83.176 говорит, что ничего не найдено.
